name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 升级到 v4，解决 node 版本警告

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Pagefind Search Index
        run: npx pagefind --site . 

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=. --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
